<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MOL-HSK-DEV0011" ignored="0" name="Default test" tests="13" failures="1" timestamp="28 Feb 2018 14:00:51 GMT" time="764.414" errors="0">
  <testcase name="a_Home" time="66.037" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="b_News" time="73.063" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="c_US" time="73.67" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="d_Sports" time="114.189" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="e_TVShowbiz" time="55.453" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="f_Australia" time="40.193" classname="cljCheck.AllMenuSubMenuNav">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at config.Retry.retry(Retry.java:37)
at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1163)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:616)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f_Australia -->
  <testcase name="g_Femail" time="63.747" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="h_Health" time="37.603" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="i_Science" time="38.726" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="j_Money" time="102.243" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="k_Video" time="19.569" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="l_Travel" time="54.456" classname="cljCheck.AllMenuSubMenuNav"/>
  <testcase name="m_FashionFinder" time="10.719" classname="cljCheck.AllMenuSubMenuNav"/>
</testsuite> <!-- Default test -->
